# general settings
# name: debug_DBCNN_LIVEC
#name: debug001_HyperNet_KonIQ10k
name: 004_HyperNet_wafer
model_type: GeneralIQAModel 
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 123

# dataset and data loader settings
datasets:
  train:
    name: koniq10k
    type: GeneralNRDataset
    dataroot_target: /data1/zengzk/wafer_IQA/wafer_2024/datasets/wafer/512*384
    meta_info_file: /data1/zengzk/wafer_IQA/wafer_2024/datasets/meta_info/meta_info_waferDataset.csv
    split_file: /data1/zengzk/wafer_IQA/wafer_2024/datasets/meta_info/wafer_official.pkl
    mos_range: [0, 100]
    lower_better: false 
    mos_normalize: true

    augment:
      hflip: true
      random_crop: 224
    img_range: 1

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: 4

  val:
    name: koniq10k
    type: GeneralNRDataset
    dataroot_target: /data1/zengzk/wafer_IQA/wafer_2024/datasets/wafer/512*384
    meta_info_file: /data1/zengzk/wafer_IQA/wafer_2024/datasets/meta_info/meta_info_waferDataset.csv
    split_file: /data1/zengzk/wafer_IQA/wafer_2024/datasets/meta_info/wafer_official.pkl
    mos_range: [0, 100]
    lower_better: false 
    mos_normalize: true

    num_worker_per_gpu: 1
    batch_size_per_gpu: 2

# network structures
network:
  type: HyperNet
  pretrained: false

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim:
    type: AdamW
    lr: !!float 5e-5
    weight_decay: !!float 1e-5

  scheduler:
    type: MultiStepLR
    milestones: [100, 200]
    gamma: 0.5

  total_epoch: 100
  warmup_iter: -1  # no warm up

  # losses
  mos_loss_opt:
    type: L1Loss 
    loss_weight: !!float 1.0
  
  metric_loss_opt:
    type: NiNLoss 
    loss_weight: !!float 1.0

# validation settings
val:
  val_freq: !!float 100
  save_img: false
  pbar: true

  key_metric: srcc # if this metric improve, update all metrics. If not specified, each best metric results will be updated separately
  metrics:
    srcc:
      type: calculate_srcc

    plcc:
      type: calculate_plcc

    krcc:
      type: calculate_krcc

# logging settings
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 5e9
  save_latest_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
